#version: '3.8'services: web:  build: .  image: todo-app:v2.1  ports:   - "5000:5000"
  deploy:
   replicas: 3
   update_config:
    parallelism: 2
    delay: 10s
  restart_policy:
   condition: on-failure  volumes:   - todo-data:/app/data  environment:   - FLASK_ENV=productionvolumes: todo-data:
  driver: local